#!/usr/bin/env python3
"""Assemble chapter files from story units. Run from the project root.

  assemble.py            # every chapter in data/chapters.csv
  assemble.py 3 4        # only chapters 3 and 4
  assemble.py --list     # show which units land in which chapter, and orphans

Chapter files are GENERATED. Edit units (content/units/*.md) and data/chapters.csv,
then re-run. Hand edits to chapters/*.typ are overwritten.
"""
import csv, re, sys
from pathlib import Path
import yaml

HEADER = "// GENERATED by chapter-generator from content/units. Edit the units, not this file.\n"


def load_units():
    out = []
    for p in sorted(Path("content/units").glob("U*.md")):
        text = p.read_text(encoding="utf-8")
        m = re.match(r"^---\n(.*?)\n---\n(.*)$", text, re.S)
        if not m: continue
        fm = yaml.safe_load(m.group(1)) or {}
        body = m.group(2)
        shaped = body.split("## Shaped", 1)[1] if "## Shaped" in body else ""
        shaped = shaped.split("\n## Notes", 1)[0].strip()
        out.append((fm, shaped, p.name))
    return out


def esc_str(s):
    return str(s).replace("\\", "\\\\").replace('"', '\\"')


def chapter_text(ch, units, show_contents):
    """Chapter opener from data/chapters.csv columns: title, chapter (number), setting,
    dates (falls back to date_range), summary_line, epigraph + epigraph_source and optional
    epigraph_2 + epigraph_2_source, columns (1 or 2)."""
    num = ch.get("number") or ch.get("chapter")
    lines = ['#import "/book/template.typ": *', HEADER.rstrip(), ""]
    args = [f'"{esc_str(ch["title"])}"']
    if num and str(num).replace(".", "").isdigit() and float(num) == int(float(num)):
        args.append(f"number: {int(float(num))}")
    if ch.get("setting"): args.append(f'setting: "{esc_str(ch["setting"])}"')
    dates = ch.get("dates") or ch.get("date_range")
    if dates: args.append(f'dates: "{esc_str(dates)}"')
    if ch.get("summary_line"): args.append(f"summary: [{ch['summary_line']}]")
    eps = [(ch.get(k), ch.get(k + "_source", "")) for k in ("epigraph", "epigraph_2") if ch.get(k)]
    if eps:
        args.append("epigraphs: (" + "".join(f'([{t}], "{esc_str(src)}"), ' for t, src in eps) + ")")
    if show_contents and ch.get("contents"): args.append(f"contents: [{ch['contents']}]")
    cols = str(ch.get("columns") or "1").strip()
    args.append(f"columns: {2 if cols == '2' else 1}")
    lines += [f"#show: chapter.with({', '.join(args)})", ""]
    sections = [u[0].get("section") for u in units]
    multi_section = len({s for s in sections if s}) > 1
    last_section = None
    for i, (fm, shaped, fname) in enumerate(units):
        lines.append(f"// ---- {fm['id']} {fm.get('title', '')} ({fname})")
        sec = fm.get("section")
        if multi_section and sec and sec != last_section and sec != ch["title"]:
            lines += [f"== {sec}", ""]
        elif i > 0 and fm.get("break_before", True):
            lines += ["#sectionbreak", ""]
        last_section = sec
        if fm.get("lead_in"):
            if fm.get("lead_in_approved"):
                lines += [str(fm["lead_in"]), "// src: lead-in approved by the author", ""]
            else:
                lines += [f"#bridge[{fm['lead_in']}]", ""]
        if fm.get("status") not in ("shaped", "approved"):
            lines += [f"#note[{fm['id']} not shaped yet]", ""]
        lines += [shaped, ""]
    return "\n".join(lines).rstrip() + "\n"


def main():
    args = sys.argv[1:]
    try:
        show_contents = bool(yaml.safe_load(open("book.yaml"))["print"].get("in_chapter_contents"))
    except Exception:
        show_contents = False
    chapters = list(csv.DictReader(open("data/chapters.csv", encoding="utf-8")))
    units = load_units()
    by_ch = {}
    orphans = []
    for u in units:
        c = str(u[0].get("chapter") or "").strip()
        (by_ch.setdefault(c, []) if c else orphans).append(u)
    for c in by_ch:
        by_ch[c].sort(key=lambda u: (float(u[0].get("order") or 999), u[0]["id"]))

    if "--list" in args:
        for ch in chapters:
            n = ch["chapter"]
            ids = [u[0]["id"] for u in by_ch.get(n, [])]
            print(f"{n:>3} {ch['title'][:40]:40} {len(ids):>3} units  {' '.join(ids)}")
        known = {ch["chapter"] for ch in chapters}
        stray = [u[0]["id"] for c, us in by_ch.items() if c not in known for u in us]
        print(f"Unassigned units: {' '.join(u[0]['id'] for u in orphans) or 'none'}")
        if stray: print(f"Units pointing at chapters not in chapters.csv: {' '.join(stray)}")
        return

    only = set(a for a in args if not a.startswith("-"))
    for ch in chapters:
        n = ch["chapter"]
        if only and n not in only: continue
        us = by_ch.get(n, [])
        if not us:
            print(f"chapter {n}: no units assigned, skipped"); continue
        path = Path(ch["file"]); path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(chapter_text(ch, us, show_contents), encoding="utf-8")
        bridges = sum(1 for fm, _, _ in us if fm.get("lead_in") and not fm.get("lead_in_approved"))
        print(f"chapter {n}: {path} ({len(us)} units, {bridges} bridges pending)")
    if orphans:
        print(f"WARNING {len(orphans)} units have no chapter: {' '.join(u[0]['id'] for u in orphans)}")


if __name__ == "__main__":
    main()
