#!/usr/bin/env python3
"""Pipeline runtime generated by the factory. One CLI; behavior comes from pipeline.yaml.

Run from a PROJECT folder (e.g. fixture/). The pipeline's pipeline.yaml is found next to
this script's parent folder, or via $PIPELINE_HOME.

  pl.py init                 new project folders + an empty gates.yaml
  pl.py ingest               checksum every file in sources/ into ledger/sources.json
  pl.py status               every stage, gate and blocker; what to do next
  pl.py coverage             every source line is in a unit or in excluded.csv
  pl.py check [--final]      all invariants (sources unchanged, citations, tiers, coverage,
                             hand edits, bridges, gates); exit 1 on any failure
  pl.py assemble [--final]   units + map.csv -> build/<output> with a GENERATED header
  pl.py build [--final]      assemble, then run the builder -> output/
  pl.py gate G1 [--by NAME]  record a human decision in gates.yaml
  pl.py questions            batch every open question, grouped by the gate that needs it
  pl.py snapshot LABEL [--major]   git commit + tag; copy output/ to output/versions/<tag>/
                                   with MANIFEST.json pinning inputs and source checksums

Invariants enforced here (see docs/FACTORY.md in the factory for why):
  sources immutable and checksummed; every claim cites back into its unit's own spans;
  units cover every source line; outputs generated, never hand-edited; anything the model
  adds is a bridge, and the final build fails while one is unapproved; named gates; versions
  pin outputs to exact inputs.
"""
import csv, datetime, hashlib, json, os, re, shutil, subprocess, sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("pyyaml is required: pip install pyyaml")

HOME = Path(os.environ.get("PIPELINE_HOME") or Path(__file__).resolve().parent.parent)
SPEC = yaml.safe_load((HOME / "pipeline.yaml").read_text())
NAME = SPEC["name"]
SRC = SPEC["source"]
UNIT = SPEC["unit"]
TIERS = [t["id"] for t in SPEC["tiers"]]
OUT = SPEC["output"]
GATES = SPEC["gates"]
STAGES = ["ingest", "units", "assemble", "build", "final"]

SOURCES = Path(SRC.get("dir", "sources"))
LEDGER = Path("ledger/sources.json")
UNITS = Path("units")
EXCLUDED = Path("excluded.csv")
MAP = Path("map.csv")
GATES_FILE = Path("gates.yaml")
BUILD = Path("build")
OUTPUT = Path("output")
GEN_LEDGER = BUILD / ".generated.json"
EXT = {"markdown": "md", "typst": "typ", "html": "html"}[OUT.get("format", "markdown")]
GENERATED = {"md": "<!-- GENERATED by {n} pl.py from units/ and map.csv. Edit the units, not this file. -->",
             "typ": "// GENERATED by {n} pl.py from units/ and map.csv. Edit the units, not this file.",
             "html": "<!-- GENERATED by {n} pl.py from units/ and map.csv. Edit the units, not this file. -->"}[EXT].format(n=NAME)

# ---- citations ------------------------------------------------------------------------
# A citation format like "[{source}:{line}]" becomes a regex; {line} may be a range "4-7".
def citation_regex(fmt):
    rx = re.escape(fmt).replace(r"\{source\}", r"(?P<source>[A-Za-z0-9_.-]+)").replace(r"\{line\}", r"(?P<line>\d+(?:-\d+)?)")
    return re.compile(rx)

CITE = citation_regex(SRC.get("citation", "[{source}:{line}]"))
SPAN = re.compile(r"^(?P<source>[A-Za-z0-9_.-]+):(?P<a>\d+)(?:-(?P<b>\d+))?$")
BRIDGE = re.compile(r"\[\[bridge (?P<id>[A-Za-z0-9_-]+):\s*(?P<text>.*?)\]\]", re.S)


def sha(p):
    h = hashlib.sha256()
    with open(p, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""): h.update(chunk)
    return h.hexdigest()


def source_files():
    return sorted(p for p in SOURCES.glob("*") if p.is_file() and not p.name.startswith("."))


def source_lines(stem):
    p = next((f for f in source_files() if f.stem == stem), None)
    return None if p is None else p.read_text(encoding="utf-8").splitlines()


def parse_span(s):
    m = SPAN.match(s.strip())
    if not m: return None
    a = int(m["a"]); b = int(m["b"] or a)
    return m["source"], a, b


# ---- units ---------------------------------------------------------------------------------
def load_units():
    out = []
    for p in sorted(UNITS.glob("U*.md")):
        t = p.read_text(encoding="utf-8")
        m = re.match(r"^---\n(.*?)\n---\n(.*)$", t, re.S)
        if not m:
            out.append(({"id": p.stem, "_error": "no frontmatter"}, "", p)); continue
        fm = yaml.safe_load(m[1]) or {}
        body = m[2]
        text = body.split("## Text", 1)[1].split("\n## ", 1)[0].strip() if "## Text" in body else ""
        out.append((fm, text, p))
    return out


def paragraphs(text):
    return [p.strip() for p in re.split(r"\n\s*\n", text) if p.strip() and not p.strip().startswith("<!--")]


# ---- gates -----------------------------------------------------------------------------------
def gates_state():
    return (yaml.safe_load(GATES_FILE.read_text()) or {}) if GATES_FILE.exists() else {}


def gate_ok(gid):
    return bool((gates_state().get(gid) or {}).get("approved"))


def gates_before(stage):
    """Gates that must be approved before `stage` may run."""
    idx = STAGES.index(stage)
    return [g for g in GATES if STAGES.index(g["after"]) < idx]


# ---- checks ----------------------------------------------------------------------------------
def check_sources(problems):
    if not LEDGER.exists():
        problems.append("sources not ingested: run `pl.py ingest`"); return
    led = json.loads(LEDGER.read_text())
    now = {p.name: sha(p) for p in source_files()}
    for name, h in led.items():
        if name not in now: problems.append(f"source {name} is missing (sources are never deleted)")
        elif now[name] != h: problems.append(f"source {name} CHANGED since ingest (sources are immutable)")
    for name in now:
        if name not in led: problems.append(f"source {name} is not in the ledger: run `pl.py ingest`")


def coverage(report=False):
    covered = {}
    for fm, _, _ in load_units():
        for s in fm.get("spans") or []:
            sp = parse_span(s)
            if sp: covered.setdefault(sp[0], set()).update(range(sp[1], sp[2] + 1))
    if EXCLUDED.exists():
        for r in csv.DictReader(open(EXCLUDED, encoding="utf-8")):
            sp = parse_span(r["span"])
            if sp: covered.setdefault(sp[0], set()).update(range(sp[1], sp[2] + 1))
    missing = []
    total = 0
    for f in source_files():
        lines = f.read_text(encoding="utf-8").splitlines()
        for i, line in enumerate(lines, 1):
            if not line.strip(): continue
            total += 1
            if i not in covered.get(f.stem, set()): missing.append(f"{f.stem}:{i}")
    if report:
        print(f"source lines: {total}; uncovered: {len(missing)}")
        for m in missing[:40]: print(f"  UNCOVERED {m}")
    return missing


def check_units(problems, final):
    seen = set()
    for fm, text, p in load_units():
        uid = fm.get("id", p.stem)
        if fm.get("_error"): problems.append(f"{p.name}: {fm['_error']}"); continue
        if uid in seen: problems.append(f"{p.name}: duplicate id {uid}")
        seen.add(uid)
        if fm.get("tier") not in TIERS:
            problems.append(f"{uid}: tier {fm.get('tier')!r} is not one of {TIERS}")
        spans = [parse_span(s) for s in fm.get("spans") or []]
        if not spans or None in spans:
            problems.append(f"{uid}: spans missing or malformed (use source:line or source:a-b)"); continue
        for src, a, b in spans:
            lines = source_lines(src)
            if lines is None: problems.append(f"{uid}: span cites unknown source {src}")
            elif b > len(lines): problems.append(f"{uid}: span {src}:{a}-{b} runs past the end ({len(lines)} lines)")
        allowed = {(s, n) for s, a, b in spans for n in range(a, b + 1)}
        approved = set(fm.get("bridges_approved") or [])
        for i, para in enumerate(paragraphs(text), 1):
            bare = BRIDGE.sub("", para).strip()
            cites = list(CITE.finditer(para))
            if bare and not cites:
                problems.append(f"{uid} paragraph {i}: no citation (every claim cites back)")
            for c in cites:
                a, _, b = c["line"].partition("-")
                for n in range(int(a), int(b or a) + 1):
                    if (c["source"], n) not in allowed:
                        problems.append(f"{uid} paragraph {i}: cites {c.group(0)} outside this unit's spans")
                        break
            if final:
                for br in BRIDGE.finditer(para):
                    if br["id"] not in approved:
                        problems.append(f"{uid}: bridge {br['id']} is not approved (final build blocked)")


def check_generated(problems):
    if not GEN_LEDGER.exists(): return
    for name, h in json.loads(GEN_LEDGER.read_text()).items():
        p = BUILD / name
        if p.exists() and sha(p) != h:
            problems.append(f"build/{name} was edited by hand; edit the units and re-assemble")


def run_checks(final=False, quiet=False):
    problems = []
    check_sources(problems)
    check_units(problems, final)
    unc = coverage()
    if unc: problems.append(f"{len(unc)} source line(s) not covered by any unit or excluded.csv (pl.py coverage)")
    check_generated(problems)
    if final:
        for g in GATES:
            if not gate_ok(g["id"]): problems.append(f"gate {g['id']} ({g['name']}) not approved")
    if not quiet:
        print("\n".join(f"PROBLEM: {p}" for p in problems) or "All checks pass.")
    return problems


# ---- assemble / build --------------------------------------------------------------------------
def render_bridges(text, approved, final):
    def rep(m):
        if m["id"] in approved: return m["text"]
        return m["text"] if final else f"⟦BRIDGE {m['id']}: {m['text']}⟧"
    return BRIDGE.sub(rep, text)


def cmd_assemble(final=False):
    for g in gates_before("assemble"):
        if not gate_ok(g["id"]): sys.exit(f"STOP at gate {g['id']}: {g['name']}. Run `pl.py questions`, then `pl.py gate {g['id']}`.")
    probs = run_checks(final=final, quiet=True)
    if final and probs:
        print("\n".join(f"PROBLEM: {p}" for p in probs)); sys.exit("final build blocked")
    units = {fm["id"]: (fm, text) for fm, text, _ in load_units() if "id" in fm}
    rows = list(csv.DictReader(open(MAP, encoding="utf-8")))
    title = OUT.get("title", NAME)
    L = []
    if EXT == "typ":
        L += [GENERATED, f'#set document(title: "{title}")', '#set text(font: ("Libertinus Serif",), size: 11pt)',
              '#set par(justify: true)', f"= {title}", ""]
    elif EXT == "html":
        L += ["<!doctype html>", GENERATED, f"<html><head><meta charset='utf-8'><title>{title}</title></head><body>", f"<h1>{title}</h1>"]
    else:
        L += [GENERATED, f"# {title}", ""]
    section = None
    for r in rows:
        if r["section"] != section:
            section = r["section"]
            L += [f"== {section}" if EXT == "typ" else f"<h2>{section}</h2>" if EXT == "html" else f"## {section}", ""]
        fm, text = units[r["unit"]]
        body = render_bridges(text, set(fm.get("bridges_approved") or []), final)
        if EXT == "typ":
            body = body.replace("#", "\\#").replace("[", "\\[").replace("]", "\\]").replace("@", "\\@")
        if EXT == "html":
            body = "\n".join(f"<p>{p}</p>" for p in paragraphs(body))
        L += [body, ""]
    if EXT == "html": L.append("</body></html>")
    BUILD.mkdir(exist_ok=True)
    name = f"{NAME}.{EXT}"
    (BUILD / name).write_text("\n".join(L) + "\n", encoding="utf-8")
    GEN_LEDGER.write_text(json.dumps({name: sha(BUILD / name)}, indent=1))
    print(f"assembled build/{name} from {len(rows)} units")
    return BUILD / name


def cmd_build(final=False):
    src = cmd_assemble(final)
    OUTPUT.mkdir(exist_ok=True)
    builder = str(OUT.get("builder", "none"))
    stem = f"{NAME}{'' if final else '-draft'}"
    if builder == "none":
        out = OUTPUT / f"{stem}.{EXT}"; shutil.copy2(src, out)
    elif builder == "typst":
        out = OUTPUT / f"{stem}.pdf"
        r = subprocess.run(["typst", "compile", str(src), str(out)], capture_output=True, text=True)
        if r.returncode: sys.exit(r.stderr)
    elif builder == "pandoc":
        out = OUTPUT / f"{stem}.{OUT.get('pandoc_ext', 'html')}"
        r = subprocess.run(["pandoc", str(src), "-o", str(out)], capture_output=True, text=True)
        if r.returncode: sys.exit(r.stderr)
    else:  # a shell command with {in} and {out}
        out = OUTPUT / f"{stem}.{OUT.get('ext', EXT)}"
        r = subprocess.run(builder.format(**{"in": src, "out": out}), shell=True)
        if r.returncode: sys.exit(f"builder failed: {builder}")
    print(f"built {out}")


# ---- gates, questions, status, versions ---------------------------------------------------------
def cmd_gate(args):
    gid = args[0]
    if gid not in {g["id"] for g in GATES}: sys.exit(f"unknown gate {gid}; gates: {[g['id'] for g in GATES]}")
    by = args[args.index("--by") + 1] if "--by" in args else os.environ.get("USER", "unknown")
    st = gates_state()
    st[gid] = {"approved": True, "by": by, "date": datetime.date.today().isoformat()}
    GATES_FILE.write_text(yaml.safe_dump(st, sort_keys=True))
    print(f"gate {gid} approved by {by}")


def cmd_questions():
    """Batch every open question by the gate that must answer it."""
    qs = {g["id"]: [] for g in GATES}
    first_open = next((g["id"] for g in GATES if not gate_ok(g["id"])), GATES[-1]["id"])
    for fm, text, p in load_units():
        for q in fm.get("questions") or []:
            qs[fm.get("gate", first_open)].append(f"{fm.get('id')}: {q}")
        for br in BRIDGE.finditer(text):
            if br["id"] not in set(fm.get("bridges_approved") or []):
                qs[GATES[-1]["id"]].append(f"{fm.get('id')}: approve bridge {br['id']}? \"{br['text'].strip()}\"")
    L = [f"# Open questions ({NAME})", ""]
    for g in GATES:
        state = "approved" if gate_ok(g["id"]) else "OPEN"
        L += [f"## {g['id']} · {g['name']} ({state})", g.get("question", ""), ""]
        L += [f"- {q}" for q in qs[g["id"]]] or ["- (none)"]
        L.append("")
    Path("questions.md").write_text("\n".join(L))
    print("\n".join(L))


def cmd_status():
    has = lambda p: Path(p).exists()
    units = load_units()
    unc = coverage() if has(SOURCES) else ["?"]
    stages = [
        ("ingest", has(LEDGER), f"{len(source_files())} source file(s)"),
        ("units", bool(units) and not unc, f"{len(units)} unit(s), {len(unc)} uncovered line(s)"),
        ("assemble", has(BUILD / f"{NAME}.{EXT}"), "build/ from units + map.csv"),
        ("build", any(OUTPUT.glob(f"{NAME}*")) if has(OUTPUT) else False, f"builder: {OUT.get('builder', 'none')}"),
        ("final", any(OUTPUT.glob(f"{NAME}.*")) if has(OUTPUT) else False, "all gates approved, 0 open bridges"),
    ]
    nxt = None
    for st, done, detail in stages:
        print(f" {'✓' if done else '·'} {st:9} {detail}")
        for g in [g for g in GATES if g["after"] == st]:
            ok = gate_ok(g["id"])
            print(f"   {'✓' if ok else '◆'} GATE {g['id']}: {g['name']}{'' if ok else '  ← a human decides'}")
            if not ok and done and nxt is None: nxt = f"gate {g['id']}: run `pl.py questions`, decide, then `pl.py gate {g['id']}`"
        if not done and nxt is None: nxt = f"stage {st}"
    print(f"\nNEXT: {nxt}" if nxt else "\nAll stages complete.")


def git(*a, check=True):
    r = subprocess.run(["git", *a], capture_output=True, text=True)
    if check and r.returncode: sys.exit(f"git {' '.join(a)} failed:\n{r.stderr}")
    return r.stdout.strip()


def cmd_snapshot(args):
    label = next((a for a in args if not a.startswith("--")), "snapshot")
    major = "--major" in args
    probs = run_checks(quiet=True)
    if any("CHANGED" in p or "edited by hand" in p for p in probs):
        sys.exit("STOP: " + "; ".join(p for p in probs if "CHANGED" in p or "edited by hand" in p))
    if not Path(".git").exists() and git("rev-parse", "--is-inside-work-tree", check=False) != "true":
        git("init", "-q")
    tags = [t for t in git("tag", "--list", "v*", check=False).splitlines() if re.match(r"v\d+\.\d+$", t)]
    vs = sorted(tuple(map(int, t[1:].split("."))) for t in tags)
    M, m = vs[-1] if vs else (0, 0)
    tag = f"v{M + 1}.0" if major else f"v{M}.{m + 1}"
    git("add", "-A", "."); git("commit", "-q", "--allow-empty", "-m", f"{tag} {label}", check=False)
    commit = git("rev-parse", "HEAD")
    git("tag", "-a", tag, "-m", label)
    dest = OUTPUT / "versions" / tag
    dest.mkdir(parents=True, exist_ok=True)
    outs = {}
    for p in OUTPUT.glob("*"):
        if p.is_file(): shutil.copy2(p, dest / p.name); outs[p.name] = sha(p)
    manifest = {"version": tag, "label": label, "date": datetime.datetime.now().isoformat(timespec="seconds"),
                "input_commit": commit, "sources": json.loads(LEDGER.read_text()) if LEDGER.exists() else {},
                "outputs": outs, "gates": gates_state(), "open_problems": probs}
    (dest / "MANIFEST.json").write_text(json.dumps(manifest, indent=2))
    print(f"{tag}: inputs @ {commit[:10]}, outputs in {dest}")


def cmd_ingest():
    LEDGER.parent.mkdir(parents=True, exist_ok=True)
    led = json.loads(LEDGER.read_text()) if LEDGER.exists() else {}
    added = []
    for p in source_files():
        h = sha(p)
        if p.name in led and led[p.name] != h:
            sys.exit(f"STOP: {p.name} changed since it was ingested. Sources are immutable: add a new file instead.")
        if p.name not in led: led[p.name] = h; added.append(p.name)
    LEDGER.write_text(json.dumps(led, indent=1, sort_keys=True))
    print(f"ledger: {len(led)} source(s), {len(added)} new")


def cmd_init():
    for d in (SOURCES, UNITS, BUILD, OUTPUT, LEDGER.parent): d.mkdir(parents=True, exist_ok=True)
    if not MAP.exists(): MAP.write_text("section,unit\n")
    if not EXCLUDED.exists(): EXCLUDED.write_text("span,reason\n")
    if not GATES_FILE.exists(): GATES_FILE.write_text("{}\n")
    print(f"project ready: put originals in {SOURCES}/ and run `pl.py ingest`")


if __name__ == "__main__":
    a = sys.argv[1:] or ["status"]
    final = "--final" in a
    cmds = {"init": cmd_init, "ingest": cmd_ingest, "status": cmd_status,
            "coverage": lambda: sys.exit(1 if coverage(report=True) else 0),
            "check": lambda: sys.exit(1 if run_checks(final) else 0),
            "assemble": lambda: cmd_assemble(final), "build": lambda: cmd_build(final),
            "gate": lambda: cmd_gate(a[1:]), "questions": cmd_questions,
            "snapshot": lambda: cmd_snapshot(a[1:])}
    if a[0] not in cmds: sys.exit(__doc__)
    cmds[a[0]]()
