#import "/book/template.typ": *
// GENERATED by chapter-generator from content/units. Edit the units, not this file.

#show: chapter.with("Others in the Family", number: 1, setting: "Norway and Duluth", dates: "about 1900", summary: [On Boots and Ore Boats], columns: 2)

// ---- U001 The boots (U001-the-boots.md)
#descent(
  ([Anders Calder (link from Norway unconfirmed)], none),
  ([Ruth's father], none),
  ([Ruth Calder (b. 1938)], [Walt]),
  ([their children and grandchildren], none),
)

#opening[What Ruth knew][about her grandfather came to her the way most family history
comes: from her father, who told it often. Where the records and the family part company,
this chapter says so; for Anders, no records have been consulted yet, so everything here is
the family's account.]

The Calders came from Norway.#idx("Calder, Anders", "Norway") Anders Calder crossed the Atlantic on a ship at sixteen, "or
that's what my father always said," Ruth added, and he did it in one pair of boots, which he
wore the whole way across. "My father loved to tell that one."
// src: [S1 00:00:02]-[S1 00:00:19]
// tier: told by her father

In Duluth#idx("Duluth, Minnesota") he found work on the ore boats#idx("ore boats"), loading iron ore at the docks. "That's where the
work was," Ruth said.
// src: [S1 00:00:21]-[S1 00:00:28]
// tier: told by her father

#records(
  [_What this chapter rests on._ Two passages of Ruth's recorded interview (session S1).
   No documents have been consulted. A passenger list or naturalization record would confirm
   or correct the crossing; see facts/gaps.md.],
)
