#import "/book/template.typ": *
// GENERATED by chapter-generator from content/units. Edit the units, not this file.

#show: chapter.with("The Ore Dock", number: 2, setting: "Duluth, Minnesota", dates: "1938–1950", summary: [On Tin Pails and Tunnels], columns: 1)

// ---- U002 The ore dock (U002-the-ore-dock.md)
#opening[Ruth Calder was born][in Duluth, Minnesota, in 1938.]
// src: book.yaml (birth year and place, confirmed by the family)

When she was seven or eight, as best she remembered, Ruth walked her father's lunch down to
the ore dock#idx("Duluth, Minnesota!ore dock") in a tin pail. The dock was so tall "you had to tip your head all the way back,"
and the trains ran right out on top of it. Whether it frightened her, she never quite
settled: "No. Well, yeah. A little."
// src: [S1 00:00:29]-[S1 00:00:47]

#plate("/photos/print/P001.png", caption: "Placeholder: a photograph of the ore dock", width: 3.6in, id: "P001")

// ---- U003 The big snow (U003-the-big-snow.md)
#sectionbreak

The big snow#idx("big snow, around 1950") came around 1950, as Ruth remembered it. The school closed for a week, and she
and her brother Pete dug a tunnel from the porch to the street. Pete proposed that they live
in it. "Mother did not agree."
// src: [S1 00:00:48]-[S1 00:01:04]
