#import "/book/template.typ": *
// GENERATED by chapter-generator from content/units. Edit the units, not this file.

#show: chapter.with("Walt and the Cabin", number: 3, setting: "Minneapolis and Pike Lake", dates: "1956–1968", summary: [On Shoes, Sore Feet and a Roof], columns: 1)

// ---- U004 The shoes (U004-the-shoes.md)
#opening[In 1956 Ruth went][down to Minneapolis for three years of nursing school.]#idx("Minneapolis, Minnesota", "nursing school") The
students lived in a dormitory, and the house mother inspected their shoes every morning.
"Every morning! As if the patients were going to look at our shoes."
// src: [S2 00:00:03]-[S2 00:00:16]

// ---- U005 The dance (U005-the-dance.md)
#sectionbreak

#bridge[Three years later, the thing she remembered best about Minneapolis had nothing to do with nursing.]

She met Walt#idx("Calder, Walt") at a church dance in 1959. Walt could not dance at all; he stepped on her feet
the whole night and then asked if he could walk her home. "I said, well, my feet can't take
much more of this, but all right."
// src: [S2 00:00:17]-[S2 00:00:35]

// ---- U006 The cabin (U006-the-cabin.md)
#sectionbreak

Starting in 1964 or so, Ruth and Walt built a cabin on Pike Lake#idx("Pike Lake, Minnesota") with their own hands. It
took four summers. Walt#idx("Calder, Walt!the cabin") did the walls and Ruth did the roof, because Walt was afraid of
heights. "Nobody believes that," she said.
// src: [S2 00:00:36]-[S2 00:00:49]

#plate("/photos/print/P002.png", caption: "Placeholder: the cabin on Pike Lake", width: 3.6in, id: "P002")

What she valued most about it was simple. "The lake was always there. Whatever else
happened, the lake was always there."
// src: [S2 00:00:50]-[S2 00:01:02]
